### ISSUE TITLE
It's  so wonderfull! Could the app remap other Fn Key, like f12

### ISSUE THREAD

**Issue by xuxinliang** [csavalas/HotkeyMapper#1] opened 2024-06-08 15:27 UTC
It's  so wonderfull! Could the app remap other Fn Key, like f12

**Comment by rh45-one** [comment] 2024-06-08 18:41
The F12 key can be remapped through Lenovo Vantage.

**Comment by xuxinliang** [comment] 2024-06-10 12:45
> The F12 key can be remapped through Lenovo Vantage.

How about F8?

**Comment by xuxinliang** [comment] 2024-06-10 12:50
I have found that
Fn+S=Alt+PrtScrn
Fn+B=Ctrl+Break
Fn+K=Scroll
Fn+Tab,can be customized by Ex_13。
Fn+P

**Comment by csavalas** [comment] 2024-06-10 16:19
I haven't tried other keys before, but, after checking just now, it looks like F4-F8 may be customizable through the same method as well:

F4: Ex_1A
F5: Ex_10
F6: Ex_0F
F7: 7
F8:  5

**Comment by csavalas** [comment] 2024-06-10 16:28
I just confirmed that customizing F4, F7, and F8 works perfectly. While F5/F6 can be customized as well, they still adjust the brightness alongside whatever mapping is set, so not ideal.

**Comment by csavalas** [comment] 2024-06-10 16:34
FYI...
F12: Ex_90

**Comment by xuxinliang** [comment] 2024-06-11 14:13
> FYI... F12: Ex_90

It is so amazing!

how to find relation between fn and ex_###?

I just want to know the way to customize  "Fn+ space"

**Comment by xuxinliang** [comment] 2024-06-11 14:24
> I just confirmed that customizing F4, F7, and F8 works perfectly. While F5/F6 can be customized as well, they still adjust the brightness alongside whatever mapping is set, so not ideal.

May be different model had the different key. 
Could you show me the way to get the relation between Fn and the code, like ex_###.
My model is T14S(gen 1), F8(with code 5) does not work.

**Comment by csavalas** [comment] 2024-06-12 00:47
@xuxinliang 

Hey there, I am actually in the process of making this work for older gens too, so maybe we can help each other (since I don't have access to an older ThinkPad lol).

As you probably already know, the registry key we care about is located here:
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Lenovo\ShortcutKey\AppLaunch`

Under that key, certain subkeys relate to different F-keys on the keyboard. Here is a chart I put together for my P1 Gen 6

```
 F4: Ex_1A
 F5: Ex_10
 F6: Ex_0F
 F7: 7
 F8: 5
 F9: Ex_96
F10: Ex_97
F11: Ex_98
F12: Ex_90
```

If you could make me a similar chart for yours, that'd be awesome!

Here's how to do that:

- Download a program called Process Monitor from [here](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon):
- Run the program
    - When you open it up, it will be filling up with events rapidly...
        - Press `CTRL` + `E` to toggle off event capture
        - Press `CTRL` + `X` to clear the already captured events
    -  Create two event filters by...
        - Press `CTRL` + `L` to open the filter window
        - Create a filter with the following specs:
            - `Process Name` + `is` + `SHTCTKY.EXE` + `Include`
        - Press `Add`
        - Create another filter with the following specs: `Operation` + `is` + `RegOpenKey` + `Include`
        - Press `Add`
        - Press `Apply`
        - Close the filter window

Ok, now you're ready to go. Repeat the following steps for each key (F4-F12):

1. Press `CTRL` + `E` to toggle on event capture
2. Press the desired `F-key` (`F4`-`F12`)
3. At least a few events should appear
4. Press `CTRL` + `E` to toggle off event capture
5. Look for an entry whose path contains: `HKLM\SOFTWARE\Lenovo\ShortcutKey\AppLaunch`
    - Take note of the subkey after `AppLaunch`, that is the subkey corresponding to the `F-key` you pressed in `step 2`
        - E.g. For the path `HKLM\SOFTWARE\Lenovo\ShortcutKey\AppLaunch\Ex_97`, we would take note of just the subkey `Ex_97`
6. Press `CTRL` + `X` to clear the captured events

Let me know if you have troubles with any of that, and post your F4-F12 chart whenever you can, thanks!

**Comment by xuxinliang** [comment] 2024-06-13 09:09
I follow your steps , and get the same results as you.
 F4: Ex_1A
 F5: Ex_10
 F6: Ex_0F
 F7: 7
 F8: 5
 F9: Ex_96
F10: Ex_97
F11: Ex_98
F12: Ex_90

But F4, F5, F6, F7,  F8 and F12 didn't work(can't be customized), remaining the original function.
Only F9, F10, F11, Fn+Tab works.

**Comment by csavalas** [comment] 2024-06-13 17:14
Thanks for doing that, and having looked at [this](https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_T14s_Gen_1_Intel/ThinkPad_T14s_Gen_1_Intel_Spec.PDF), it actually makes sense that you got the same result--I saw _'gen 1'_ and assumed it was a much older model.

That being said, can you elaborate on what exactly you are doing, step-by-step, to try to remap F8, for example?

**Comment by csavalas** [comment] 2024-06-13 17:28
[F8Test.zip](https://github.com/user-attachments/files/15826244/F8Test.zip)

@xuxinliang Here, just to narrow this down, try merging this file with your registry. Once merged, pressing F8 should open a new browser window to https://github.com. Let me know if it does

**Comment by xuxinliang** [comment] 2024-06-13 21:39
> [F8Test.zip](https://github.com/user-attachments/files/15826244/F8Test.zip)
> 
> @xuxinliang Here, just to narrow this down, try merging this file with your registry. Once merged, pressing F8 should open a new browser window to https://github.com. Let me know if it does

it works!   :-):-)

With F8、F12
The path ("File"="%SystemRoot%\\system32\\notepad.exe") did not work.

The path ("File"="C:\\Windows\\notepad.exe") worked。

With Fn+tab
"File"="%SystemRoot%\\system32\\notepad.exe" worked.
So I copy the path to  F8,

**Comment by csavalas** [comment] 2024-06-13 21:41
Great! I just released a new version that supports all of the keys from F4-F12, check it out!


![main](https://github.com/csavalas/HotkeyMapper/assets/60337327/974eb421-4118-4c70-b6d6-046987eca81d)

**Comment by xuxinliang** [comment] 2024-06-13 21:44
> Great! I just released a new version that supports all of the keys from F4-F12, check it out!
> 
> ![main](https://private-user-images.githubusercontent.com/60337327/339561694-974eb421-4118-4c70-b6d6-046987eca81d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTUyMjUsIm5iZiI6MTcxODMxNDkyNSwicGF0aCI6Ii82MDMzNzMyNy8zMzk1NjE2OTQtOTc0ZWI0MjEtNDExOC00YzcwLWI2ZDYtMDQ2OTg3ZWNhODFkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDIxNDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZWFiZDQ2MWNiZjg2MThiNDdhOTk2OTFhODIxZWVjYjkyZjE3OGI0NmM4NzQ2ZjYyNTJkZjYzZGRmMmMyMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dZSYwdHeAJZopRF3ShqyAMo8rX2WCK3IcjuYTUqlBFw)

great, thank you. :-)

**Closed as completed** 2024-06-18 19:50 UTC
